spring:
  datasource:
    url: jdbc:postgresql://technomarketdb.internal:5432/postgres
    username: postgres
    password: sPAC4JTlduaAUSe
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
myapp:
  image-path: file:///Users/techno_market_image