spring:
  profiles:
    active: dev
    include: secret
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  data:
    jpa:
      repositories:
        enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: rhkddhks12@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
            logging:
              level:
                org.springframework.mail: DEBUG



